# the rate of wolf-man in total population
wolf-man-rate: 0.2
normal-wolf-countdown: 90
crazy-wolf-countdown: 90
game-length: 1200
end-game-length: 150

# when the game starts, teleport every playing player to this location
game-start-location:
  x: -278
  y: 83
  z: -63
  
# this currently doesnt do anything
spawn-location:
  x: -250
  y: 136
  z: -63