# This is the config file for Milkyway Vote Plugin.
# For detailed information, you can visit https://github.com/GHYNG/MW-Minecraft-Server-Plugins

# The language used for this plugin.
# You can always add new language files.
# Note: Use full file name with extension.
language: 'lang.yml'