name: MW_Block_Protection
version: Paper-1.18.1-MW-1.4
description: This plugin protects blocks from different entities, including players, from illegal ways to break them.
author: GHYNG
main: org.mwage.mcPlugin.block_protection.Main
depend: [MW_Plugin_Main]
api-version: 1.16