name: MW_Chat_Command
version: Paper-1.16.5-MW-1.1
description: This plugin gives owners of the server some powerful commands without op permission. 
author: GHYNG
main: org.mwage.mcPlugin.chat_command.Main
depend: [MW_Plugin_Main]
softdepend: [MW_Chat]
api-version: 1.16