name: MW_World_Management
version: Paper-1.16.5-MW-1.3.1
description: This plugin manages different worlds.
author: GHYNG
main: org.mwage.mcPlugin.world_management.Main
depend: [MW_Plugin_Main]
api-version: 1.16