name: MW_Player_Death_Message
version: Paper-1.16.5-MW-1.2
description: This plugin tells players the location and other information when they die.
author: GHYNG
main: org.mwage.mcPlugin.player_death_message.Main
depend: [MW_Plugin_Main]
api-version: 1.16