name: MW_Event_Zhongqiu
version: Paper-1.17.1-MW-1
description: Milkyway event plugin Zhongqiu.
author: GHYNG
main: org.mwage.mcPlugin.event_zhongqiu.Main
depend: [MW_Plugin_Main]
api-version: 1.16

commands:
  zhongqiu:
    description: commands about mw event "zhongqiu".
    usage: /zhongqiu help for detailed information.
    permission: mw_event_zhongqiu
    
permissions:
  mw_event_zhongqiu:
    description: permission for calling the /zhongqiu commands.
    default: op