name: MW_Block_Protection
version: Paper-1.16.5-MW-1
description: This plugin protects blocks from different entities, including players, from illegal ways to break them.
author: GHYNG
main: org.mwage.mcPlugin.block_protection.Main